GLOBAL.setfenv(1, GLOBAL)

AddAdventureLevel({
	id = "DARKNESS",
	name = STRINGS.UI.SANDBOXMENU.ADVENTURELEVELS[6],
	location = "forest",
	version = 4,
	min_playlist_position = 5,
	max_playlist_position = 5,
	overrides = {
		branching = "never",
		task_set = "DARKNESS",
		wanderingtrader_enabled = "none",
		start_location = "NightmareStart",
		has_ocean = false,
		specialevent = "none",

		day = "onlynight",
		season_start = "autumn",
		autumn = "default",
		winter = "noseason",
		spring = "noseason",
		summer = "noseason",
		weather = "often",
		boons = "always",
		roads = "never",
		berrybush = "never",
		spiders = "often",
		fireflies = "always",
		start_node = "BGGrass",
		maxwelllight_area = "always",
		bearger = "never",
		dragonfly = "never",
		goosemoose = "never",
		stageplays = "never",
		junkyard = "never",
		balatro = "never",
		terrariumchest = "never",

		prefabswaps_start = "classic",
		petrification = "none",
		portalresurection      = "none",
		ghostenabled           = "always",
		ghostsanitydrain       = "always",
		basicresource_regrowth = "none",
		spawnmode              = "fixed",
		resettime              = "default",
	},
	substitutes = MergeMaps(
		{ ["pighouse"] = { perstory = 1, weight = 1, pertask = 1 } },
		AdventureModeGetRandomSubstituteList(ADVENTURE_MODE_SUBS_1, 3)
	),
})
