GLOBAL.setfenv(1, GLOBAL)

AddAdventureLevel({
	id = "ENDING",
	name = STRINGS.UI.SANDBOXMENU.ADVENTURELEVELS[7],
	location = "forest",
	nomaxwell = true,
	version = 4,
	min_playlist_position = 6,
	max_playlist_position = 6,
	overrides = {
		task_set = "ENDING",
		wanderingtrader_enabled = "none",
		start_location = "MaxHomeStart",
		has_ocean = false,
		keep_disconnected_tiles = true,
		no_wormholes_to_disconnected_tiles = true,
		no_joining_islands = true,
		layout_mode = "LinkNodesByKeys",
		roads = "default",
		specialevent = "none",

		islands = "always",
		day = "onlynight",
		autumn = "default",
		winter = "noseason",
		spring = "noseason",
		summer = "noseason",
		weather = "never",
		creepyeyes = "always",
		waves = "off",
		boons = "never",
		bearger = "never",
		dragonfly = "never",
		goosemoose = "never",
		hounds = "never",

		stageplays = "never",
		junkyard = "never",
		balatro = "never",
		terrariumchest = "never",

		prefabswaps_start = "classic",
		petrification = "none",
		portalresurection      = "none",
		ghostenabled           = "always",
		ghostsanitydrain       = "always",
		basicresource_regrowth = "none",
		spawnmode              = "fixed",
		resettime              = "default",
	},
	-- hideminimap = true,
	teleportaction = "restart",
	teleportmaxwell = "ADVENTURE_6_TELEPORTFAIL",
})
