GLOBAL.setfenv(1, GLOBAL)

AddAdventureLevel({
	id = "HUB",
	name = "HUB",
	location = "forest",
	version = 4,
	overrides = {
		task_set = "HUB",
		start_location = "PreSummerStart",
		has_ocean = false,
		wanderingtrader_enabled = "none",
		specialevent = "none",

		day = "longdusk",
		-- start_node = "Clearing",
		autumn = "noseason",
		winter = "noseason",
		spring = "default",
		summer = "noseason",
		season_start = "winter",
		spiders = "often",
		branching = "default",
		loop = "never",
		bearger = "never",
		dragonfly = "never",
		goosemoose = "never",
		deerclops = "never",

		stageplays = "never",
		junkyard = "never",
		balatro = "never",
		terrariumchest = "never",

		prefabswaps_start = "classic",
		petrification = "none",
		portalresurection      = "none",
		ghostenabled           = "always",
		ghostsanitydrain       = "always",
		basicresource_regrowth = "none",
		spawnmode              = "fixed",
		resettime              = "default",
	},
	substitutes = AdventureModeGetRandomSubstituteList(ADVENTURE_MODE_SUBS_1, 3),
})
