GLOBAL.setfenv(1, GLOBAL)

AddAdventureLevel({
	id = "RAINY",
	name = STRINGS.UI.SANDBOXMENU.ADVENTURELEVELS[1],
	location = "forest",
	version = 4,
	min_playlist_position = 1,
	max_playlist_position = 3,
	overrides = {
		task_set = "RAINY",
		start_location = "WinterStartEasy",
		has_ocean = false,
		wanderingtrader_enabled = "none",
		specialevent = "none",
		world_size = "default",
		day = "longdusk",
		weather = "squall",
		frograin = "often",

		start_node = "Forest",
		season_start = "autumn",
		autumn = "veryshortseason",
		winter = "veryveryshortseason",
		spring = "noseason",
		summer = "noseason",
		
		deerclops = "never",
		bearger = "never",
		dragonfly = "never",
		goosemoose = "never",
		hounds = "never",
		mactusk = "always",
		leifs = "always",
		trees = "often",
		carrot = "default",
		berrybush = "never",

		stageplays = "never",
		junkyard = "never",
		balatro = "never",
		terrariumchest = "never",

		prefabswaps_start = "classic",
		petrification = "none",
		portalresurection      = "none",
		ghostenabled           = "always",
		ghostsanitydrain       = "always",
		basicresource_regrowth = "none",
		spawnmode              = "fixed",
		resettime              = "default",
	},
	substitutes = AdventureModeGetRandomSubstituteList(ADVENTURE_MODE_SUBS_1, 3),
})
