GLOBAL.setfenv(1, GLOBAL)

AddAdventureLevel({
	id = "WINTER",
	name = STRINGS.UI.SANDBOXMENU.ADVENTURELEVELS[2],
	location = "forest",
	version = 4,
	min_playlist_position = 1,
	max_playlist_position = 4,
	overrides = {
		task_set = "WINTER",
		wanderingtrader_enabled = "none",
		day = "longdusk",
		start_location = "WinterStartMedium",
		has_ocean = false,
		start_node = "Clearing",
		loop = "never",
		branching = "least",
		autumn = "noseason",
		winter = "default",
		spring = "noseason",
		summer = "noseason",
		season_start = "winter",
		weather = { "always", "often" },
		deerclops = "often",
		bearger = "never",
		dragonfly = "never",
		goosemoose = "never",
		hounds = "never",
		mactusk = "always",
		carrot = "never",
		berrybush = "rare",

		stageplays = "never",
		junkyard = "never",
		balatro = "never",
		terrariumchest = "never",
		specialevent = "none",

		prefabswaps_start = "classic",
		petrification = "none",
		portalresurection      = "none",
		ghostenabled           = "always",
		ghostsanitydrain       = "always",
		basicresource_regrowth = "none",
		spawnmode              = "fixed",
		resettime              = "default",
	},
	substitutes = AdventureModeGetRandomSubstituteList(ADVENTURE_MODE_SUBS_1, 1),
})
