AddTaskSet("DARKNESS", {
	tasks = {
		"Swamp start",
		"Battlefield",
		"Walled Kill the spiders",
		"Sanity-Blocked Spider Queendom",
	},
	numoptionaltasks = 2,
	optionaltasks = {
		"Killer bees!",
		"Chessworld",
		"Tentacle-Blocked The Deep Forest",
		"Tentacle-Blocked Spider Swamp",
		"Trapped Forest hunters",
		"Waspy The hunters",
		"Hounded Magic meadow",
	},
	set_pieces = {
		["RuinedBase"] = { tasks = {
			"Swamp start",
			"Battlefield",
			"Walled Kill the spiders",
			"Killer bees!",
		} },
		["ResurrectionStoneLit"] = { count = 4, tasks = {
			"Swamp start",
			"Battlefield",
			"Walled Kill the spiders",
			"Sanity-Blocked Spider Queendom",
			"Killer bees!",
			"Chessworld",
			"Tentacle-Blocked The Deep Forest",
			"Tentacle-Blocked Spider Swamp",
			"Trapped Forest hunters",
			"Waspy The hunters",
			"Hounded Magic meadow",
		} },
	},
	ordered_story_setpieces = {
		"TeleportatoRingLayout",
		"TeleportatoBoxLayout",
		"TeleportatoCrankLayout",
		"TeleportatoPotatoLayout",
		"TeleportatoBaseAdventureLayout",
	},
	required_prefabs = {
		"teleportato_ring",
		"teleportato_box",
		"teleportato_crank",
		"teleportato_potato",
		"teleportato_base",
		"chester_eyebone",
	},
})
