AddTaskSet("HUB", {
	tasks = {
		"Resource-Rich",
		"Lots-o-Spiders",
		"Lots-o-Tentacles",
		"Lots-o-Tallbirds",
		"Lots-o-Chessmonsters",
	},
	numoptionaltasks = 4,
	optionaltasks = {
		"The hunters",
		"Trapped Forest hunters",
		"Wasps and Frogs and bugs",
		"Tentacle-Blocked The Deep Forest",
		"Hounded Greater Plains",
		"Merms ahoy",
	},
	set_pieces = {
		["SimpleBase"] = { tasks = {
			"Lots-o-Spiders",
			"Lots-o-Tentacles",
			"Lots-o-Tallbirds",
			"Lots-o-Chessmonsters",
		} },
		["WesUnlock"] = { restrict_to = "background", tasks = {
			"The hunters",
			"Trapped Forest hunters",
			"Wasps and Frogs and bugs",
			"Tentacle-Blocked The Deep Forest",
			"Hounded Greater Plains",
			"Merms ahoy",
		} },
		["ResurrectionStone"] = { count = 1, tasks = {
			"Resource-Rich",
			"Lots-o-Spiders",
			"Lots-o-Tentacles",
			"Lots-o-Tallbirds",
			"Lots-o-Chessmonsters",
			"The hunters",
			"Trapped Forest hunters",
			"Wasps and Frogs and bugs",
			"Tentacle-Blocked The Deep Forest",
			"Hounded Greater Plains",
			"Merms ahoy",
		} },
	},
	ordered_story_setpieces = {
		"TeleportatoRingLayout",
		"TeleportatoBoxLayout",
		"TeleportatoCrankLayout",
		"TeleportatoPotatoLayout",
		"TeleportatoBaseAdventureLayout",
	},
	required_prefabs = {
		"spawnpoint_master",
		"teleportato_ring",
		"teleportato_box",
		"teleportato_crank",
		"teleportato_potato",
		"teleportato_base",
		"chester_eyebone",
	},
})
