AddTaskSet("RAINY", {
	tasks = {
		"Make a pick",
		"Easy Blocked Dig that rock",
		"Great Plains",
		"Guarded Speak to the king",
	},
	numoptionaltasks = 4,
	optionaltasks = {
		"Waspy Beeeees!",
		"Guarded Squeltch",
		"Guarded Forest hunters",
		"Befriend the pigs",
		"Guarded For a nice walk",
		"Walled Kill the spiders",
		"Killer bees!",
		"Make a Beehat",
		"Waspy The hunters",
		"Hounded Magic meadow",
		"Wasps and Frogs and bugs",
		"Guarded Walrus Desolate",
	},
	set_pieces = {
		["WesUnlock"] = { restrict_to = "background", tasks = {
			"Easy Blocked Dig that rock",
			"Great Plains",
			"Guarded Speak to the king",
			"Waspy Beeeees!",
			"Guarded Squeltch",
			"Guarded Forest hunters",
			"Befriend the pigs",
			"Guarded For a nice walk",
			"Walled Kill the spiders",
			"Killer bees!",
			"Make a Beehat",
			"Waspy The hunters",
			"Hounded Magic meadow",
			"Wasps and Frogs and bugs",
			"Guarded Walrus Desolate",
		} },
		["ResurrectionStoneWinter"] = { count = 1, tasks = {
			"Make a pick",
			"Easy Blocked Dig that rock",
			"Great Plains",
			"Guarded Speak to the king",
			"Waspy Beeeees!",
			"Guarded Squeltch",
			"Guarded Forest hunters",
			"Befriend the pigs",
			"Guarded For a nice walk",
			"Walled Kill the spiders",
			"Killer bees!",
			"Make a Beehat",
			"Waspy The hunters",
			"Hounded Magic meadow",
			"Wasps and Frogs and bugs",
			"Guarded Walrus Desolate",
		} },
	},
	ordered_story_setpieces = {
		"TeleportatoRingLayout",
		"TeleportatoBoxLayout",
		"TeleportatoCrankLayout",
		"TeleportatoPotatoLayout",
		"TeleportatoBaseAdventureLayout",
	},
	required_prefabs = {
		"spawnpoint_master",
		"teleportato_ring",
		"teleportato_box",
		"teleportato_crank",
		"teleportato_potato",
		"teleportato_base",
		"chester_eyebone",
	},
})
