AddLevel(LEVELTYPE.SURVIVAL, {
    id = "ADVENTURE_SECONDARY",
    name = "ADVENTURE_SECONDARY",
    desc = "ADVENTURE_SECONDARY",
    location = "cave",
    version = 4,
    overrides = {
        is_adventure = true,
        task_set = "ADVENTURE_SECONDARY",
        start_location = "AdventureSecondaryStart",
        world_size = "small",
        layout_mode = "LinkNodesByKeys",
        roads = "never",
        boons = "never",
        has_ocean = false,
        keep_disconnected_tiles = true,
        no_wormholes_to_disconnected_tiles = true,
        no_joining_islands = true,
    },
    required_setpieces = {},
    numrandom_set_pieces = 0,
    random_set_pieces = {},
    required_prefabs = {},
})
